pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:https://github.com/erdodo/dodOS.git
          - cd dodOS.git
          - git push --mirror git@github.com:https://github.com/erdodo/dodOS.git