

definitions:
  services:
    docker:
      memory: 1024
  
  steps:
    - step: &Push-to-GitHub
        name: Push code changes to GitHub
        image: alpine/git:1.0.26
        services:
          - docker
        caches:
          - docker
        script:
          - git remote add github "git@github.com:erdodo/dodOS.git"
          - git checkout $BITBUCKET_BRANCH
          - git pull
          - git push github $BITBUCKET_BRANCH


  
pipelines:
  default:
    - step:
        name: Run automated API tests using Postman CLI
        image: atlassian/default-image:3
        script:
          # Install Postman CLI
          - curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
          # Login using your API Key
          - postman login --with-api-key $POSTMAN_API_KEY
          # Run your collection using Postman CLI
          - postman collection run "17278905-ac60b8c1-14a4-4caf-80c6-d780d6cc56b8" -e "17278905-759251b2-6c6e-4bd7-aa6a-5451314f6e79"
  branches:
    master:
      - step: *Push-to-GitHub
    sandbox:
      - step: *Push-to-GitHub              
    staging:
      - step: *Push-to-GitHub              
    production:
      - step: *Push-to-GitHub  